version: '3.8'
services:
  rest:
    restart: unless-stopped
    image: andytakker/insperia-lms-backend:latest
    command: python -m lms
    ports:
      - 8000:80
    environment:
      APP_API_ADDRESS: 0.0.0.0
      APP_API_PORT: 80

      APP_API_SECRET_KEY: ${SECRET_KEY}

      APP_PG_DSN: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}

      APP_TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      APP_TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}

      APP_SOHO_API_TOKEN: ${SOHO_API_TOKEN}

      APP_GOOGLE_KEYS: ${GOOGLE_KEYS}

  cron:
    restart: unless-stopped
    image: andytakker/insperia-lms-backend:latest
    command: python -m lms.cron

    environment:
      APP_PG_DSN: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}

      APP_GOOGLE_KEYS: ${GOOGLE_KEYS}

      APP_REGULAR_NOTIFICATION_URL: ${REGULAR_NOTIFICATION_URL}
      APP_SUBSCRIPTION_NOTIFICATION_URL: ${SUBSCRIPTION_NOTIFICATION_URL}
      APP_ADDITIONAL_NOTIFICATION_URL: ${ADDITIONAL_NOTIFICATION_URL}

networks:
  default:
    external: true
    name: academy
