version: '3.8'
services:
  backend:
    restart: unless-stopped
    image: andytakker/insperia-lms-backend:latest
    environment:
      APP_SOHO_API_TOKEN: ${SOHO_API_TOKEN}
      APP_API_SECRET_KEY: ${SECRET_KEY}
      APP_PG_DSN: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgetset.ru:5433/${POSTGRES_DB}

    ports:
      - 8000:80
