version: '3.8'
services:
  backend:
    restart: unless-stopped
    image: andytakker/insperia-lms-backend:latest
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      SOHO_API_TOKEN: ${SOHO_API_TOKEN}
      SECRET_KEY: ${SECRET_KEY}

    ports:
      - 8000:80

  # worker:
  #   restart: unless-stopped
  #   image: andytakker/insperia-lms-worker:latest
  #   depends_on:
  #     - backend
  #   environment:
  #     POSTGRES_HOST: ${POSTGRES_HOST}
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}

  #     SOHO_API_TOKEN: ${SOHO_API_TOKEN}
  #     SECRET_KEY: ${SECRET_KEY}

  cron:
    restart: unless-stopped
    image: andytakker/insperia-lms-cron:latest
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      SOHO_API_TOKEN: ${SOHO_API_TOKEN}
      SECRET_KEY: ${SECRET_KEY}
