[tool.poetry]
name = "new-lms"
version = "0.1.0"
description = "New LMS for Insperia School with Soho.LMS"
authors = ["Sergey Natalenko <sergey.natalenko@mail.ru>"]
license = "MIT"
readme = "README.md"
packages = [{include = "new_lms"}]

[tool.poetry.dependencies]
python = "^3.11"
pydantic-settings = "^2.0.3"
SQLAlchemy = "^2.0.20"
loguru = "^0.7.0"
sqlalchemy-utils = "^0.41.1"
httpx = "^0.24.1"
pydantic = {extras = ["email"], version = "^2.3.0"}
celery = "^5.3.4"

[tool.poetry.group.backend.dependencies]
fastapi = "^0.101.1"
alembic = "^1.11.3"
uvicorn = "^0.23.2"
asyncpg = "^0.28.0"
python-jose = "^3.3.0"
gunicorn = "^21.2.0"

[tool.poetry.group.worker.dependencies]
psycopg2-binary = "^2.9.7"
google-api-service-helper = "^0.0.6"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
mypy = "^1.5.1"
types-python-jose = "^3.3.4.8"
pytest = "^7.4.1"
httpx = "^0.24.1"
pytest-asyncio = "^0.21.1"
pytest-randomly = "^3.15.0"
pytest-deadfixtures = "^2.2.1"
factory-boy = "^3.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ["py311"]

[tool.isort]
known_local_folder = "src"
py_version = "311"
profile = "black"

[tool.mypy]
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
ignore_missing_imports = false
no_implicit_optional = true

[[tool.mypy.overrides]]
module = "gunicorn.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "sqlalchemy_utils.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "celery.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "google_api_service_helper.*"
ignore_missing_imports = true