"""Add strict constraints

Revision ID: ceb94a697647
Revises: 380f544ad907
Create Date: 2023-10-01 18:08:45.925271

"""
from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ceb94a697647"
down_revision: str | None = "380f544ad907"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq__student_product__student_id_product_id"),
        "student_product",
        ["student_id", "product_id"],
    )
    op.create_check_constraint(
        op.f("ck__student_product__check_teacher"),
        table_name="student_product",
        condition="(teacher_type IS NULL) = (teacher_product_id IS NULL)",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq__student_product__student_id_product_id"),
        "student_product",
        type_="unique",
    )
    op.drop_constraint(
        op.f("ck__student_product__check_teacher"), "student_product", type_="check"
    )
    # ### end Alembic commands ###
