"""
Init db.

Revision ID: 42738fd46e63
Revises:
Create Date: 2023-09-05 09:00:45.288387

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42738fd46e63"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("eng_name", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__product_group")),
    )
    op.create_index(
        op.f("ix__product_group__eng_name"), "product_group", ["eng_name"], unique=False,
    )
    op.create_index(
        op.f("ix__product_group__name"), "product_group", ["name"], unique=False,
    )
    op.create_table(
        "setting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.String(length=2048), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__setting")),
    )
    op.create_index(op.f("ix__setting__key"), "setting", ["key"], unique=True)
    op.create_table(
        "student",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("vk_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("last_name", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__student")),
        sa.UniqueConstraint("vk_id", name=op.f("uq__student__vk_id")),
    )
    op.create_table(
        "subject",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("eng_name", sa.String(), nullable=False),
        sa.Column("autopilot_url", sa.String(length=1024), nullable=True),
        sa.Column("group_vk_link", sa.String(length=1024), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__subject")),
    )
    op.create_index(op.f("ix__subject__eng_name"), "subject", ["eng_name"], unique=True)
    op.create_index(op.f("ix__subject__name"), "subject", ["name"], unique=False)
    op.create_table(
        "teacher",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vk_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("last_name", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__teacher")),
    )
    op.create_index(op.f("ix__teacher__vk_id"), "teacher", ["vk_id"], unique=True)
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("product_group_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_group_id"],
            ["product_group.id"],
            name=op.f("fk__product__product_group_id__product_group"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subject.id"],
            name=op.f("fk__product__subject_id__subject"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__product")),
    )
    op.create_index(op.f("ix__product__name"), "product", ["name"], unique=False)
    op.create_index(
        op.f("ix__product__product_group_id"),
        "product",
        ["product_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__product__subject_id"), "product", ["subject_id"], unique=False,
    )
    op.create_table(
        "soho",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("mail", sa.String(length=128), nullable=False),
        sa.Column("student_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name=op.f("fk__soho__student_id__student"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__soho")),
        sa.UniqueConstraint("mail", name=op.f("uq__soho__mail")),
        sa.UniqueConstraint("student_id", name=op.f("uq__soho__student_id")),
    )
    op.create_table(
        "offer",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=2048), nullable=False),
        sa.Column("cohort", sa.Integer(), nullable=False),
        sa.Column("teacher_type", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk__offer__product_id__product"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__offer")),
        sa.UniqueConstraint("name", name=op.f("uq__offer__name")),
    )
    op.create_index(op.f("ix__offer__cohort"), "offer", ["cohort"], unique=False)
    op.create_index(
        op.f("ix__offer__product_id"), "offer", ["product_id"], unique=False,
    )
    op.create_table(
        "teacher_product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("max_students", sa.Integer(), nullable=False),
        sa.Column("average_rate", sa.Float(), nullable=False),
        sa.Column("rate_counter", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk__teacher_product__product_id__product"),
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teacher.id"],
            name=op.f("fk__teacher_product__teacher_id__teacher"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__teacher_product")),
    )
    op.create_index(
        op.f("ix__teacher_product__product_id"),
        "teacher_product",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__teacher_product__teacher_id"),
        "teacher_product",
        ["teacher_id"],
        unique=False,
    )
    op.create_table(
        "student_product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("teacher_product_id", sa.Integer(), nullable=True),
        sa.Column("teacher_type", sa.String(length=16), nullable=True),
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("cohort", sa.Integer(), nullable=False),
        sa.Column("teacher_rate", sa.Integer(), nullable=False),
        sa.Column("teacher_rate_date", sa.Date(), nullable=False),
        sa.Column("expulsion_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offer.id"],
            name=op.f("fk__student_product__offer_id__offer"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk__student_product__product_id__product"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name=op.f("fk__student_product__student_id__student"),
        ),
        sa.ForeignKeyConstraint(
            ["teacher_product_id"],
            ["teacher_product.id"],
            name=op.f("fk__student_product__teacher_product_id__teacher_product"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__student_product")),
    )
    op.create_index(
        op.f("ix__student_product__cohort"), "student_product", ["cohort"], unique=False,
    )
    op.create_index(
        op.f("ix__student_product__expulsion_at"),
        "student_product",
        ["expulsion_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix__student_product__offer_id"),
        "student_product",
        ["offer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__student_product__product_id"),
        "student_product",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__student_product__student_id"),
        "student_product",
        ["student_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__student_product__teacher_product_id"),
        "student_product",
        ["teacher_product_id"],
        unique=False,
    )
    op.create_table(
        "teacher_assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_product_id", sa.Integer(), nullable=False),
        sa.Column("teacher_product_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("assignment_at", sa.DateTime(), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk__teacher_assignment__product_id__product"),
        ),
        sa.ForeignKeyConstraint(
            ["student_product_id"],
            ["student_product.id"],
            name=op.f("fk__teacher_assignment__student_product_id__student_product"),
        ),
        sa.ForeignKeyConstraint(
            ["teacher_product_id"],
            ["teacher_product.id"],
            name=op.f("fk__teacher_assignment__teacher_product_id__teacher_product"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__teacher_assignment")),
    )
    op.create_index(
        op.f("ix__teacher_assignment__product_id"),
        "teacher_assignment",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__teacher_assignment__student_product_id"),
        "teacher_assignment",
        ["student_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__teacher_assignment__teacher_product_id"),
        "teacher_assignment",
        ["teacher_product_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__teacher_assignment__teacher_product_id"),
        table_name="teacher_assignment",
    )
    op.drop_index(
        op.f("ix__teacher_assignment__student_product_id"),
        table_name="teacher_assignment",
    )
    op.drop_index(
        op.f("ix__teacher_assignment__product_id"), table_name="teacher_assignment",
    )
    op.drop_table("teacher_assignment")
    op.drop_index(
        op.f("ix__student_product__teacher_product_id"), table_name="student_product",
    )
    op.drop_index(op.f("ix__student_product__student_id"), table_name="student_product")
    op.drop_index(op.f("ix__student_product__product_id"), table_name="student_product")
    op.drop_index(op.f("ix__student_product__offer_id"), table_name="student_product")
    op.drop_index(
        op.f("ix__student_product__expulsion_at"), table_name="student_product",
    )
    op.drop_index(op.f("ix__student_product__cohort"), table_name="student_product")
    op.drop_table("student_product")
    op.drop_index(op.f("ix__teacher_product__teacher_id"), table_name="teacher_product")
    op.drop_index(op.f("ix__teacher_product__product_id"), table_name="teacher_product")
    op.drop_table("teacher_product")
    op.drop_index(op.f("ix__offer__product_id"), table_name="offer")
    op.drop_index(op.f("ix__offer__cohort"), table_name="offer")
    op.drop_table("offer")
    op.drop_table("soho")
    op.drop_index(op.f("ix__product__subject_id"), table_name="product")
    op.drop_index(op.f("ix__product__product_group_id"), table_name="product")
    op.drop_index(op.f("ix__product__name"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix__teacher__vk_id"), table_name="teacher")
    op.drop_table("teacher")
    op.drop_index(op.f("ix__subject__name"), table_name="subject")
    op.drop_index(op.f("ix__subject__eng_name"), table_name="subject")
    op.drop_table("subject")
    op.drop_table("student")
    op.drop_index(op.f("ix__setting__key"), table_name="setting")
    op.drop_table("setting")
    op.drop_index(op.f("ix__product_group__name"), table_name="product_group")
    op.drop_index(op.f("ix__product_group__eng_name"), table_name="product_group")
    op.drop_table("product_group")
    # ### end Alembic commands ###
