"""Add verified work

Revision ID: 380f544ad907
Revises: 596282007903
Create Date: 2023-09-21 22:41:50.534529

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "380f544ad907"
down_revision: str | None = "596282007903"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verified_work_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=True),
        sa.Column("file_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name=op.f("fk__verified_work_file__student_id__student"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subject.id"],
            name=op.f("fk__verified_work_file__subject_id__subject"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__verified_work_file")),
    )
    op.create_index(
        op.f("ix__verified_work_file__file_id"),
        "verified_work_file",
        ["file_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix__verified_work_file__student_id"),
        "verified_work_file",
        ["student_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__verified_work_file__subject_id"),
        "verified_work_file",
        ["subject_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__verified_work_file__subject_id"), table_name="verified_work_file"
    )
    op.drop_index(
        op.f("ix__verified_work_file__student_id"), table_name="verified_work_file"
    )
    op.drop_index(
        op.f("ix__verified_work_file__file_id"), table_name="verified_work_file"
    )
    op.drop_table("verified_work_file")
    # ### end Alembic commands ###
