"""New migration

Revision ID: 30fe539613c5
Revises: 42738fd46e63
Create Date: 2023-09-14 02:08:59.852002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30fe539613c5"
down_revision: Union[str, None] = "42738fd46e63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviewer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("last_name", sa.String(length=128), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("teacher_product_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("desired", sa.Integer(), nullable=False),
        sa.Column("max_", sa.Integer(), nullable=False),
        sa.Column("abs_max", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk__reviewer__product_id__product"),
        ),
        sa.ForeignKeyConstraint(
            ["teacher_product_id"],
            ["teacher_product.id"],
            name=op.f("fk__reviewer__teacher_product_id__teacher_product"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__reviewer")),
    )
    op.add_column(
        "product",
        sa.Column("check_spreadsheet_id", sa.String(length=256), nullable=False),
    )
    op.add_column(
        "product", sa.Column("drive_folder_id", sa.String(length=256), nullable=False)
    )
    op.add_column("product", sa.Column("start_date", sa.Date(), nullable=True))
    op.add_column("product", sa.Column("end_date", sa.Date(), nullable=True))
    op.create_index(
        op.f("ix__product__end_date"), "product", ["end_date"], unique=False
    )
    op.create_index(
        op.f("ix__product__start_date"), "product", ["start_date"], unique=False
    )
    op.drop_constraint("uq__soho__mail", "soho", type_="unique")
    op.create_unique_constraint(op.f("uq__soho__email"), "soho", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq__soho__email"), "soho", type_="unique")
    op.create_unique_constraint("uq__soho__mail", "soho", ["email"])
    op.drop_index(op.f("ix__product__start_date"), table_name="product")
    op.drop_index(op.f("ix__product__end_date"), table_name="product")
    op.drop_column("product", "end_date")
    op.drop_column("product", "start_date")
    op.drop_column("product", "drive_folder_id")
    op.drop_column("product", "check_spreadsheet_id")
    op.drop_table("reviewer")
    # ### end Alembic commands ###
