"""Add flowproduct

Revision ID: 010d01c2d522
Revises: 4ababa1032c8
Create Date: 2023-10-14 12:59:42.174132

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "010d01c2d522"
down_revision: str | None = "4ababa1032c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flow_product",
        sa.Column("flow_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("soho_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["flow_id"], ["flow.id"], name=op.f("fk__flow_product__flow_id__flow")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk__flow_product__product_id__product"),
        ),
        sa.PrimaryKeyConstraint(
            "flow_id", "product_id", "soho_id", name=op.f("pk__flow_product")
        ),
        sa.UniqueConstraint("soho_id", name=op.f("uq__flow_product__soho_id")),
    )
    op.create_foreign_key(
        op.f("fk__teacher_product_flow__teacher_product_id__teacher_product"),
        "teacher_product_flow",
        "teacher_product",
        ["teacher_product_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk__teacher_product_flow__flow_id__flow"),
        "teacher_product_flow",
        "flow",
        ["flow_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__teacher_product_flow__flow_id__flow"),
        "teacher_product_flow",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk__teacher_product_flow__teacher_product_id__teacher_product"),
        "teacher_product_flow",
        type_="foreignkey",
    )
    op.drop_table("flow_product")
    # ### end Alembic commands ###
