"""Change `rate` to `grade`

Revision ID: da4abbdca2ad
Revises: 010d01c2d522
Create Date: 2023-10-16 11:47:51.510649

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da4abbdca2ad"
down_revision: str | None = "010d01c2d522"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###t
    op.alter_column("teacher_product", "rate_counter", new_column_name="grade_counter")
    op.alter_column("teacher_product", "average_rate", new_column_name="average_grade")
    op.alter_column("student_product", "teacher_rate", new_column_name="teacher_grade")
    op.alter_column(
        "student_product",
        "teacher_rate_date",
        new_column_name="teacher_graded_at",
        type_=sa.DateTime,
        existing_type=sa.Date,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("teacher_product", "grade_counter", new_column_name="rate_counter")
    op.alter_column("teacher_product", "average_grade", new_column_name="average_rate")
    # ### end Alembic commands ###
