pytest_plugins = (
    "tests.plugins.arguments",
    "tests.plugins.autopilot",
    "tests.plugins.database",
    "tests.plugins.distributor",
    "tests.plugins.factories.flow",
    "tests.plugins.factories.offer",
    "tests.plugins.factories.product",
    "tests.plugins.factories.soho",
    "tests.plugins.factories.student",
    "tests.plugins.factories.subject",
    "tests.plugins.factories.teacher",
    "tests.plugins.rest",
    "tests.plugins.soho",
    "tests.plugins.telegram",
)
