pytest_plugins = (
    "tests.plugins.instances.arguments",
    "tests.plugins.instances.autopilot",
    "tests.plugins.instances.database",
    "tests.plugins.instances.distributor",
    "tests.plugins.factories.flow",
    "tests.plugins.factories.offer",
    "tests.plugins.factories.product",
    "tests.plugins.factories.soho",
    "tests.plugins.factories.student",
    "tests.plugins.factories.subject",
    "tests.plugins.factories.teacher_assignment",
    "tests.plugins.factories.teacher",
    "tests.plugins.instances.rest",
    "tests.plugins.instances.soho",
    "tests.plugins.instances.telegram",
)
