"""Add flows

Revision ID: 30d0858c6cd2
Revises: ceb94a697647
Create Date: 2023-10-13 13:23:22.870783

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30d0858c6cd2"
down_revision: str | None = "ceb94a697647"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teacher_product_flow",
        sa.Column("teacher_product_id", sa.Integer(), nullable=False),
        sa.Column("flow_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint(
            "teacher_product_id", "flow_id", name=op.f("pk__teacher_product_flow")
        ),
    )
    op.create_table(
        "flow",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk__flow__product_id__product")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__flow")),
    )
    op.create_index(op.f("ix__flow__product_id"), "flow", ["product_id"], unique=False)
    op.add_column("student_product", sa.Column("flow_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix__student_product__flow_id"),
        "student_product",
        ["flow_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk__student_product__flow_id__flow"),
        "student_product",
        "flow",
        ["flow_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__student_product__flow_id__flow"),
        "student_product",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix__student_product__flow_id"), table_name="student_product")
    op.drop_column("student_product", "flow_id")
    op.drop_index(op.f("ix__flow__product_id"), table_name="flow")
    op.drop_table("flow")
    op.drop_table("teacher_product_flow")
    # ### end Alembic commands ###
