"""fix flows

Revision ID: 4ababa1032c8
Revises: 30d0858c6cd2
Create Date: 2023-10-14 13:30:15.566303

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ababa1032c8"
down_revision: str | None = "30d0858c6cd2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix__flow__product_id", table_name="flow")
    op.drop_constraint("fk__flow__product_id__product", "flow", type_="foreignkey")
    op.drop_column("flow", "product_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow",
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk__flow__product_id__product", "flow", "product", ["product_id"], ["id"]
    )
    op.create_index("ix__flow__product_id", "flow", ["product_id"], unique=False)
    # ### end Alembic commands ###
