"""Fix nullable subject autopilot_url

Revision ID: 2fcf93204d09
Revises: bf1b47c6d4f7
Create Date: 2023-10-27 00:00:51.208535

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fcf93204d09"
down_revision: str | None = "bf1b47c6d4f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subject",
        "autopilot_url",
        existing_type=sa.VARCHAR(length=1024),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subject", "autopilot_url", existing_type=sa.VARCHAR(length=1024), nullable=True
    )
    # ### end Alembic commands ###
