name: Check project in all branches

on:
  workflow_call:
  push:
    branches-ignore:
      - master
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  POSTGRES_USER: lms
  POSTGRES_PASSWORD: L8UtP0KEfD8b4lT
  POSTGRES_DB: test_lms

  APP_PG_DSN: postgresql+asyncpg://lms:L8UtP0KEfD8b4lT@postgres:5432/test_lms
  APP_BASE_PG_DSN: postgresql+asyncpg://lms:L8UtP0KEfD8b4lT@postgres:5432/postgres

jobs:
  checking:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: make develop-ci

      - name: Run lint
        run: make lint-ci

  test:
    name: Run service tests with pytest
    runs-on: ubuntu-22.04
    container: python:3.12
    needs: checking
    services:
      postgres:
        image: postgres:15
        env:
          TZ: UTC
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ env. POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: make develop-ci

      - name: Run pytest
        run: make test-ci
