name: Check project in all branches

on:
  workflow_call:
  push:
    branches-ignore:
      - master
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  POSTGRES_USER: lms
  POSTGRES_PASSWORD: L8UtP0KEfD8b4lT
  POSTGRES_DB: test_lms

  APP_PG_DSN: postgresql+asyncpg://lms:L8UtP0KEfD8b4lT@postgres:5432/test_lms
  APP_BASE_PG_DSN: postgresql+asyncpg://lms:L8UtP0KEfD8b4lT@postgres:5432/postgres

jobs:
  checking:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Run flake8
        run: python -m flake8 --max-line-length 88 --format=default ./lms 2>&1 | tee flake8.txt

      - name: Run black
        run: python -m black ./lms --check

      - name: Run bandit
        run: python -m bandit -ll -iii ./lms -f json -o ./bandit.json

      - name: Run mypy
        run: python -m mypy --config-file ./pyproject.toml ./lms

  test:
    name: Run service tests with pytest
    runs-on: ubuntu-22.04
    container: python:3.11-slim
    needs: checking
    services:
      postgres:
        image: postgres:15
        env:
          TZ: UTC
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ env. POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry
          poetry config virtualenvs.create false
          poetry install --no-root

      # - name: Run pytest
      #   run: python -m pytest ./tests/ --junitxml=junit/test-results.xml --cov=./lms/ --cov-report=xml
