name: Make release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  checking:
    name: Check repository
    uses: ./.github/workflows/check.yml

  build_and_push_docker:
    name: Build and push AMD64 and ARM64 images
    needs: checking
    runs-on: ubuntu-latest
    steps:

      - name: Set up tag
        id: vars
        run: echo "sha_short=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./docker/backend/backend.dockerfile
          context: ./
          tags: |
            andytakker/insperia-lms-backend:latest
            andytakker/insperia-lms-backend:${{ steps.vars.outputs.sha_short }}

      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./docker/backend/worker.dockerfile
          context: ./
          tags: |
            andytakker/insperia-lms-worker:latest
            andytakker/insperia-lms-worker:${{ steps.vars.outputs.sha_short }}

      - name: Build and push cron image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./docker/cron/cron.dockerfile
          context: ./
          tags: |
            andytakker/insperia-lms-cron:latest
            andytakker/insperia-lms-cron:${{ steps.vars.outputs.sha_short }}
